trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: install
    jobs:
      - job: install
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.28'
          - task: init
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo 'Hello world'
                terraform -version