trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: install and validate
    jobs:
      - job: install
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.28'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                terraform init
          - task: Bash@4
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                terraform validate                